#include <vtkPlot.h>
#include <vtkPlotLine.h>
#include <vtkBitArray.h>
#include <vtkCallbackCommand.h>
#include <vtkCollection.h>
#include <vtkCommand.h>
#include <vtkDataArray.h>
#include <vtkDebugLeaks.h>
#include <vtkDoubleArray.h>
#include <vtkFloatArray.h>
#include <vtkShortArray.h>
#include <vtkSignedCharArray.h>
#include <vtkUnsignedCharArray.h>
#include <vtkUnsignedLongArray.h>
#include <vtkInformation.h>
#include <vtkInformationVector.h>
#include <vtkIntArray.h>
#include <vtkLookupTable.h>
#include <vtkMath.h>
#include <vtkMultiThreader.h>
#include <vtkNew.h>
#include <vtkObject.h>
#include <vtkObjectFactory.h>
#include <vtkPoints.h>
#include <vtkSmartPointer.h>
#include <vtkStdString.h>
#include <vtkStringArray.h>
#include <vtkVersion.h>
#include <vtkWeakPointer.h>
#include <vtkBoundingBox.h>
#include <vtkCell.h>
#include <vtkColor.h>
#include <vtkDataObject.h>
#include <vtkFieldData.h>
#include <vtkImageData.h>
#include <vtkPlane.h>
#include <vtkPlanes.h>
#include <vtkPointData.h>
#include <vtkPolyData.h>
#include <vtkTable.h>
#include <vtkUnstructuredGrid.h>
#include <vtkVector.h>
#include <vtkVoxel.h>
#include <vtkAlgorithm.h>
#include <vtkAlgorithmOutput.h>
#include <vtkImageAlgorithm.h>
#include <vtkStreamingDemandDrivenPipeline.h>
#include <vtkTrivialProducer.h>
#include <vtkMatrix3x3.h>
#include <vtkMatrix4x4.h>
#include <vtkErrorCode.h>
#include <vtkTimerLog.h>
#include <vtkGeneralTransform.h>
#include <vtkHomogeneousTransform.h>
#include <vtkTransform.h>
#include <vtkAppendPolyData.h>
#include <vtkAssignAttribute.h>
#include <vtkTriangleFilter.h>
#include <vtkTubeFilter.h>
#include <vtkGeometryFilter.h>
#include <vtkSphereSource.h>
#include <vtkImageAppendComponents.h>
#include <vtkImageCast.h>
#include <vtkImageChangeInformation.h>
#include <vtkImageConstantPad.h>
#include <vtkImageExtractComponents.h>
#include <vtkImageReslice.h>
#include <vtkImageThreshold.h>
#include <vtkImageMathematics.h>
#include <vtkImageAccumulate.h>
#include <vtkImageStencil.h>
#include <vtkPNGWriter.h>
#include <vtkActor.h>
#include <vtkActor2D.h>
#include <vtkCamera.h>
#include <vtkColorTransferFunction.h>
#include <vtkImageMapper.h>
#include <vtkImageMapper3D.h>
#include <vtkProperty.h>
#include <vtkProperty2D.h>
#include <vtkRenderer.h>
#include <vtkRenderWindow.h>
#include <vtkTextProperty.h>
#include <vtkPython.h>
#include <vtkPythonUtil.h>
#include <vtksys/Directory.hxx>
#include <vtksys/RegularExpression.hxx>
#include <vtksys/SystemTools.hxx>

//Empty main just to create a target
int main() {
  return 0;
}
